# fly.toml app configuration file generated for fullstack-11-cicd on 2023-06-07T10:37:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[env]
  PORT = "8080"

app = "fullstack-11-cicd"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  http_checks = []
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.0"
